fix is multisite
log-oscon/WP-Docker-Construct pull request #8
Opened 2018-02-28 11:27 UTC by lzcalderaro

Change values on multisite.

2018-02-28 11:32 UTC, csrui approved these changes

2018-03-02 16:42 UTC, Narayon requested changes

2018-03-02 16:42 UTC, Narayon commented on bin/setup.sh
> +  * ) MULTISITE=1;;
The default should be single(0).

2018-03-05 17:20 UTC, Narayon approved these changes

2018-03-05 17:21 UTC, merged